//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalibreerMShape.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("spoorwisselmshape")]
        public string mshape {
            get {
                return ((string)(this["mshape"]));
            }
            set {
                this["mshape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GEOPOORT.VW_LRS_SPOORHARTLIJN")]
        public string lrs {
            get {
                return ((string)(this["lrs"]));
            }
            set {
                this["lrs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GEOCODE")]
        public string mshape_sleutel1 {
            get {
                return ((string)(this["mshape_sleutel1"]));
            }
            set {
                this["mshape_sleutel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GEOPOORT.VW_HECTOMETERRAAI")]
        public string raai {
            get {
                return ((string)(this["raai"]));
            }
            set {
                this["raai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double raai_afstand {
            get {
                return ((double)(this["raai_afstand"]));
            }
            set {
                this["raai_afstand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mshape_sleutel2 {
            get {
                return ((string)(this["mshape_sleutel2"]));
            }
            set {
                this["mshape_sleutel2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double mshape_maxafstand {
            get {
                return ((double)(this["mshape_maxafstand"]));
            }
            set {
                this["mshape_maxafstand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(\"GEOCODE\"=\'{0}\')")]
        public string lrs_selectie {
            get {
                return ((string)(this["lrs_selectie"]));
            }
            set {
                this["lrs_selectie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double mshape_tolerantie {
            get {
                return ((double)(this["mshape_tolerantie"]));
            }
            set {
                this["mshape_tolerantie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HMGETAL")]
        public string raai_hmgetal {
            get {
                return ((string)(this["raai_hmgetal"]));
            }
            set {
                this["raai_hmgetal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(\"GEOCODE\"=\'{0}\')")]
        public string raai_selectie {
            get {
                return ((string)(this["raai_selectie"]));
            }
            set {
                this["raai_selectie"] = value;
            }
        }
    }
}
