//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalibreerMShape.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\temp\\LRS")]
        public string inputfolder {
            get {
                return ((string)(this["inputfolder"]));
            }
            set {
                this["inputfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vw_lrs_spoortak")]
        public string mshape {
            get {
                return ((string)(this["mshape"]));
            }
            set {
                this["mshape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("spoorhartlijn")]
        public string lrs {
            get {
                return ((string)(this["lrs"]));
            }
            set {
                this["lrs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("km_begin")]
        public string mshape_kmbegin {
            get {
                return ((string)(this["mshape_kmbegin"]));
            }
            set {
                this["mshape_kmbegin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("km_eind")]
        public string mshape_kmeind {
            get {
                return ((string)(this["mshape_kmeind"]));
            }
            set {
                this["mshape_kmeind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GEOCODE")]
        public string lrs_sleutel {
            get {
                return ((string)(this["lrs_sleutel"]));
            }
            set {
                this["lrs_sleutel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GEOCODE_BE")]
        public string mshape_sleutel1 {
            get {
                return ((string)(this["mshape_sleutel1"]));
            }
            set {
                this["mshape_sleutel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hm_raai2")]
        public string raai {
            get {
                return ((string)(this["raai"]));
            }
            set {
                this["raai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GEOCODE")]
        public string raai_sleutel {
            get {
                return ((string)(this["raai_sleutel"]));
            }
            set {
                this["raai_sleutel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double raai_afstand {
            get {
                return ((double)(this["raai_afstand"]));
            }
            set {
                this["raai_afstand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GEOCODE_EI")]
        public string mshape_sleutel2 {
            get {
                return ((string)(this["mshape_sleutel2"]));
            }
            set {
                this["mshape_sleutel2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double mshape_maxafstand {
            get {
                return ((double)(this["mshape_maxafstand"]));
            }
            set {
                this["mshape_maxafstand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(NOT (\"SUBCODE\"<\'9\')) OR (\"SUBCODE\"=\'\') AND (\"GEOCODE\"=\'{0}\' OR \"GEOCODE\"=\'{1}\')")]
        public string lrs_selectie {
            get {
                return ((string)(this["lrs_selectie"]));
            }
            set {
                this["lrs_selectie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double mshape_tolerantie {
            get {
                return ((double)(this["mshape_tolerantie"]));
            }
            set {
                this["mshape_tolerantie"] = value;
            }
        }
    }
}
